name: windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch:

concurrency:
  group: windows-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  windows:
    name: ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # see https://github.com/microsoft/setup-msbuild
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Configure CMake
        shell: bash
        run: |
          mkdir build
          cd build
          cmake -D CMAKE_BUILD_TYPE=Release -DKALDI_DECODER_ENABLE_TESTS=ON ..

      - name: Build
        shell: bash
        run: |
          cd build
          cmake --build . --target ALL_BUILD --config Release
          ls -lh ./lib/Release/*
          ls -lh ./bin/Release/*

      - name: Test
        shell: bash
        run: |
          cd build
          export PYTHONPATH=$PWD/lib/Release:$PYTHONPATH
          export PYTHONPATH=$PWD/../kaldi-decoder/python:$PYTHONPATH

          ctest -C Release --output-on-failure
